apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: swagger-editor
  name: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: swagger-editor
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: swagger-editor
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: swagger-editor
        ports:
        - containerPort: 8080
        resources: {}
status: {}
