apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

# imperative command 
# k create role pod-reader --verb=get,list,watch --resource=pods
# k get role pod-reader -o yaml  
